export const MLB = {
  'Atlanta Braves': 'New York Mets',
  'Arizona Diamondbacks': 'Los Angeles Dodgers',
  'Baltimore Orioles': '1. New York Yankees',
  'Boston Red Sox': '1. New York Yankees',
  'Chicago Cubs': '1. St. Louis Cardinals',
  'Chicago White Sox': '1. Chicago Cubs',
  'Cincinnati Reds': 'St. Louis Cardinals',
  'Cleveland Indians': 'Detroit Tigers',
  'Colorado Rockies': 'Los Angeles Dodgers',
  'Detroit Tigers': 'Cleveland Indians',
  'Houston Astros': 'Texas Rangers',
  'Kansas City Royals': 'St. Louis Cardinals',
  'Los Angeles Angels of Anaheim': ' Los Angeles Dodgers',
  'Los Angeles Dodgers': 'San Francisco Giants',
  'Miami Marlins': 'Atlanta Braves',
  'Milwaukee Brewers': 'Chicago Cubs',
  'Minnesota Twins': 'New York Yankees',
  'New York Mets': 'New York Yankees',
  'New York Yankees': 'Boston Red Sox',
  'Oakland A\'s': 'San Francisco Giants',
  'Philadelphia Phillies': 'New York Mets',
  'Pittsburgh Pirates': 'St. Louis Cardinals',
  'St. Louis Cardinals': 'Chicago Cubs',
  'San Diego Padres': 'Los Angeles Dodgers',
  'San Francisco Giants': 'Los Angeles Dodgers',
  'Seattle Mariners': 'Oakland A\'s',
  'Tampa Bay Rays': 'New York Yankees',
  'Texas Rangers': 'Los Angeles Angels of Anaheim',
  'Toronto Blue Jays': 'New York Yankees',
  'Washington Nationals': 'Baltimore Orioles'
};
