export const NFL = {
  'Buffalo Bills': 'Miami Dolphins',
  'Miami Dolphins': 'New England Patriots',
  'New England Patriots': 'Colts',
  'New York Jets': 'New England Patriots',
  'Baltimore Ravens': 'Pittsburgh Steelers',
  'Cincinnati Bengals': 'Pittsburgh Steelers',
  'Cleveland Browns': 'Pittsburgh Steelers',
  'Pittsburgh Steelers': 'Cincinnati Bengals',
  'Houston Texans': 'Indianapolis Colts',
  'Indianapolis Colts': 'New England Patriots',
  'Jacksonville Jaguars': 'Tennessee Titans',
  'Denver Broncos': 'Oakland Raiders',
  'Kansas City Chiefs': 'Denver Broncos',
  'Oakland Raiders': 'Denver Broncos',
  'San Diego Chargers': 'Oakland Raiders',
  'Dallas Cowboys': 'Washington Redskins',
  'New York Giants': 'Dallas Cowboys',
  'Philadelphia Eagles': 'Dallas Cowboys',
  'Washington Redskins': 'Dallas Cowboys',
  'Chicago Bears': 'Green Bay Packers',
  'Detroit Lions': 'Green Bay Packers',
  'Green Bay Packers': 'Minnesota Vikings',
  'Minnesota Vikings': 'Green Bay Packers',
  'Atlanta Falcons': 'New Orleans Saints',
  'Carolina Panthers': 'Atlanta Falcons',
  'New Orleans Saints': 'Atlanta Falcons',
  'Tampa Bay Buccaneers': 'Atlanta Falcons',
  'Arizona Cardinals': 'Seattle Seahawks',
  'Los Angeles Rams': 'San Francisco 49ers',
  'San Francisco 49ers': 'Seattle Seahawks',
  'Seattle Seahawks': 'Arizona Cardinals'
};
