export const NHL = {
  'Flyers': 'Penguins',
  'Rangers': 'Islanders',
  'Toronto Maple Leafs': 'Ottawa Senators',
  'Bruins': 'Canadiens',
  'Tampa Bay': 'Washington Capitals',
  'Blackhawks': 'Red Wings',
  'Oilers': 'Flames',
  'Ducks': 'Kings',
  'Canucks': 'Wild',
  'Devils': 'Rangers',
  'Colorado Avalanche': 'Red Wings',
  'Sharks': 'Ducks',
  'Nashville Predators': 'Red Wings',
  'Dallas Stars': 'San Jose Sharks',
  'Blue Jackets': 'Predators',
  'St. Louis Blues': 'Blackhawks',
  'Buffalo Sabres': 'Toronto Maple Leafs',
  'Coyotes': 'Jets',
  'Carolina Hurricanes': 'Florida Panthers',
  'Penguins': 'Flyers',
  'Islanders': 'Rangers',
  'Ottawa Senators': 'Toronto Maple Leafs',
  'Canadiens': 'Bruins',
  'Washington Capitals': 'Tampa Bay',
  'Flames': 'Oilers',
  'Kings': 'Ducks',
  'Wild': 'Canucks',
  'Red Wings': 'Colorado Avalanche',
  'San Jose Sharks': 'Dallas Stars',
  'Predators': 'Blue Jackets',
  'Jets': 'Coyotes',
  'Florida Panthers': 'Carolina Hurricanes'
};
